name: Presubmit

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        # macos-12 is for the x64 (intel) architecture
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [ macos-12, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: distribution-${{ matrix.os }}
          if-no-files-found: error
          path: |
            build/compose/binaries/main/dmg/*.dmg